---
title: "About Us"
---

The Global Economic Monitoring Branch (GEMB) monitors and analyses global economic trends and prospects and their implications for the implementation of the 2030 Agenda. Using its World Economic Forecasting Model, GEMB produces globally-consistent economic forecasts for a large number of developed, emerging and developing economies. GEMB leads the production and dissemination of the [World Economic Situation and Prospects (WESP)](https://www.un-ilibrary.org/content/periodicals/24118370) – the definitive report of the United Nations system on the state of the global economy – in partnership with the United Nations Conference on Trade and Development (UNCTAD), the five United Nations Regional Commissions and the United Nations World Tourism Organization. GEMB also provides policy advice and capacity development support to developing countries on macroeconomic modelling and policy options, emphasizing the need for stronger linkages between short-term macroeconomic and long-term development policies.